name: food
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.5
  get: 4.6.5
  dio: 5.0.0
  pretty_dio_logger: 1.3.1
  internet_connection_checker: 1.0.0+1
  freezed_annotation: 2.2.0
  json_annotation: 4.8.0
  dartz: 0.10.1
  get_storage: 2.0.3
  flutter_svg: 2.0.1
  awesome_notifications: 0.7.4+1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  freezed: 2.3.2
  json_serializable: 6.6.1
  build_runner: 2.3.3
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/icons/
  uses-material-design: true

